export const START_SEARCHING = 'START_SEARCHING_SEARCH';
export const START_SEARCHING_TEACHERS = 'START_SEARCHING_TEACHERS';
export const START_SEARCHING_SUBJECTS = 'START_SEARCHING_SUBJECTS';
export const START_SEARCHING_DEGREES = 'START_SEARCHING_DEGREES';
export const SUBJECTS_FETCH = 'SUBJECTS_FETCH';
export const DEGREES_FETCH = 'DEGREES_FETCH';
export const TEACHERS_FETCH = 'TEACHERS_FETCH';
export const CHANGE_TAB = 'CHANGE_TAB';
