export const START_SEARCHING = 'START_SEARCHING_SEARCH';
export const START_SEARCHING_TEACHERS = 'START_SEARCHING_TEACHERS';
export const START_SEARCHING_SUBJECTS = 'START_SEARCHING_SUBJECTS';
export const START_SEARCHING_GRADES = 'START_SEARCHING_GRADES';
export const SUBJECTS_FETCH = 'SUBJECTS_FETCH';
export const GRADES_FETCH = 'GRADES_FETCH';
export const TEACHERS_FETCH = 'TEACHERS_FETCH';
export const CHANGE_TAB = 'CHANGE_TAB';
