export const START_SEARCHING = 'START_SEARCHING_TEACHER';
export const TEACHER_SEARCHING = 'TEACHER_SEARCHING';
export const TEACHER_FETCH = 'TEACHER_FETCH';
export const TEACHER_ERROR = 'TEACHER_ERROR';
