export const START_LOADING = 'START_LOADING_SUBJECT';
export const START_LOADING_SUBJECT = 'START_LOADING_SUBJECT';
export const SUBJECT_FETCH = 'SUBJECT_FETCH';
export const SUBJECT_ERROR = 'SUBJECT_ERROR';
