export const START_FETCHING_PROFILE = 'START_FETCHING_PROFILE';
export const ERROR_FETCHING_PROFILE = 'ERROR_FETCHING_PROFILE';
export const SUCCESS_FETCHING_PROFILE = 'SUCCESS_FETCHING_PROFILE';
export const START_EDITING_PROFILE = 'EDITING_PROFILE';
export const ERROR_EDITING_PROFILE = 'ERROR_EDITING_PROFILE';
export const SUCCESS_EDITING_PROFILE = 'SUCCESS_EDITING_PROFILE';
